goss-testing/scripts/ceph-service-status.sh

Fixes to logic issue with the ceph service check
Fixes the pdsh known host issue so the goss check doesn't put add an invalid entry
* Resolves casminst-3469
* craystack
This is a service check.  The testing was validating the results against the known state of ceph
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? n/a
- Were continuous integration tests run? If not, why? n/a
- Was upgrade tested? If not, why? n/a
- Was downgrade tested? If not, why? n/a
- Were new tests (or test issues/Jiras) created for this change? n/a
n/a

Casminst 3469 1.0

---

goss-testing/scripts/check_clock_skew.sh

Forcefully closes the persistent ssh connection if time is in sync.  The retry logic is removed since the connections are now fast enough for the test to complete.
* Resolves CASMINST-4532
* `#surtur`
Ran the script directly with a known clock out of sync
```
redbull-ncn-m001-pit:/var/www/ephemeral/jsalmela # time ./skew.sh
Warning: Permanently added 'ncn-m003,10.252.1.6' (ECDSA) to the list of known hosts.
Warning: Permanently added 'ncn-w001,10.252.1.7' (ECDSA) to the list of known hosts.
Warning: Permanently added 'ncn-w003,10.252.1.12' (ECDSA) to the list of known hosts.
Warning: Permanently added 'ncn-w002,10.252.1.8' (ECDSA) to the list of known hosts.
Warning: Permanently added 'ncn-m002,10.252.1.5' (ECDSA) to the list of known …
```

CASMINST-4532 clock skew close persistent connections

---

.github/workflows/shellcheck.yml
build-testing/boot-functions.sh
build-testing/install-ncn-images-livecd
build-testing/pxe-boot-nodes
build-testing/verify-kubernetes-cluster
goss-testing/automated/run-ncn-tests.sh
goss-testing/scripts/ceph-service-status.sh
goss-testing/scripts/check_bond_members_have_correct_mtu.sh
goss-testing/scripts/check_clock_skew.sh
goss-testing/scripts/check_k8s_loadbalancers.sh
goss-testing/scripts/check_ncn_xname.sh
goss-testing/scripts/check_no_wipe_flag.sh
goss-testing/scripts/check_static_routes.sh
goss-testing/scripts/dhcp_router_ip_check.sh
goss-testing/scripts/etcd_backups_check.sh
goss-testing/scripts/etcd_cluster_balance.sh
goss-testing/scripts/etcd_health_check.sh
goss-testing/scripts/postgres_replication_lag.sh
goss-testing/scripts/s4_preflight_checks.sh
start-goss-servers.sh

- Partially implements MTL-1497
This adds a shellcheck Action.  It's set to fail on warnings or errors.  As a starting point, I disabled the existing warnings and any future scripts will need to pass this gate.
- RFE Pull Request
Adds shellcheck workflow to this repo.
N/A
Low

MTL-1497 add shellcheck workflow

---

goss-testing/tests/ncn/goss-k8s-nexus-space.yaml

This updates the required amount of space needed for the raspberry upgrade. 
This is backwards compatible and it lessens the amount of space required.
* Resolves [CASMPET-5756](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5756)
* Documentation changes required in [CASMPET-5756](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5756)
* Mug
Checked that the size did work. This does not change the test fucntionality.

CASMPET-5756: Update space requirements for Nexus

---

start-goss-servers.sh

This PR is a slight tweak to my fix for the NCN image build issue with the goss-servers service.
This PR changes the service startup script in two ways:
1) The script waits for the run-ncn-tests library to exist on the system before sourcing it. This will now be where it waits during NCN image builds, where that library file is never installed. This will also handle the case on a live NCN where the service is started before the csm-testing RPM is installed.
2) The script will no longer retry the create_tmpvar_file function if the return code indicates that the function wasn't found (rc 127). That should be a fatal error, since a retry is never going to succeed. This should not cause image build breaks because of #1 above and, even if the library file does exist during an image build, then …

CASMINST-5169: Server startup should wait for library to exist before using it

---

goss-testing/scripts/data-validator.py
goss-testing/suites/ncn-healthcheck-master.yaml
goss-testing/tests/ncn/goss-bss-basecamp-valid.yaml

adding a script to validate NTP data in Basecamp and NTP / Boot params data in BSS
* Resolves: https://jira-pro.its.hpecorp.net:8443/browse/MTL-1646
* Resolves: https://jira-pro.its.hpecorp.net:8443/browse/MTL-1847
* Documentation changes required in docs-csm
* fanta
* mug
* redull pit
* locally
Executed on the above nodes and saw no issues with reading and verifying Basecamp / BSS data.
The script only reads and verifies data in BSS / Basecamp, so risk is none.

MTL-1646, MTL-1847, CASMINST-4281

---

goss-testing/tests/common/goss-ceph-csi-k8s-requirements.yaml
goss-testing/tests/ncn/goss-ceph-csi-storage-node-requirements.yaml
goss-testing/tests/ncn/goss-ceph-status.yaml
goss-testing/tests/ncn/goss-ceph-storage-health.yaml
goss-testing/tests/ncn/goss-ceph-storage-services.yaml
goss-testing/tests/ncn/goss-unused-drives-on-storage-nodes.yaml

backporting CASMPET-5324 for 1.3
This is changes to ceph goss test output to point to remediation steps.
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_
- Were the install/upgrade-based …

CSAMPET-5911 backport CASMPET-5324: ceph goss test output changes

---

goss-testing/scripts/k8s_kyverno_pods_running.sh
goss-testing/scripts/k8s_kyverno_polr_list.sh

Backport of https://github.com/Cray-HPE/csm-testing/pull/376

CASMINST-5088: Scripts to validate kyverno configuration. (#376)

---

goss-testing/scripts/ceph-service-status.sh

Also resolves CASMPET-5919
Edit to ceph-service-status.sh script to not prompt the user with options if osd is down. 
When this script is run during storage upgrade with argo, if an osd is down and the user is prompted, argo will break/stop.
This also resolves CASMPET-5919 by printing "ceph health detail" at the end of the script if any failure is detected.
* Resolves [CASMPET-5824](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5824)
* Resolves [CASMPET-5919](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5919)
* CrayStack
Tested output when working and when an osd was down.
- Were the …

CASMPET-5824 remove user-prompt from ceph-service-status.sh and fix start_time error

---

goss-testing/automated/run-ncn-tests.sh

Jacob, merging this will address my outstanding issues with your PR. Of course, if you object to any parts of this, let me know, and we can discuss. If you are cool with it, merge it into your PR branch and I can approve the PR.
It fixes the remaining issue in the local vars function, and makes some small formatting changes to make the new code more closely match the style of the existing functions.

VSHA-503: Set hardware manufacturer different for vshasta; adjust formatting of new code to match existing functions

---

Jenkinsfile.github
Makefile
csm-testing.spec

Minor `Jenkinsfile` and license updates. This simplifies some things in the `Jenkinsfile`, and conforms to my current template I'm using for several RPMs used in the PIT and NCN images.

Updating template for `Jenkinsfile`

---

goss-testing/suites/ncn-upgrade-tests-worker.yaml

Remove BGP neighbor check from ncn-upgrade-tests-worker goss suite. This is a temporary work around for IUF worker rebuilds. This test requires a switch password which cannot be passed in via IUF. Additional work needs to be done to put this password in vault which is why we are removing the test for now.
* Virtual …

CASMINST-5908 remove BGP neighbor check from ncn-upgrade-tests-worker goss suite

---

goss-testing/scripts/check_bgp_neighbors_established.sh

- updated check_bgp_neighbors.sh to load switch admin password from vault
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_
local
surtur
_How were the changes tested and success verified? If schema …

CASMINST-5908 - updated check_bgp_neighbors.sh to load switch admin password from vault

---

goss-testing/scripts/check_bgp_neighbors_established.sh
goss-testing/suites/ncn-upgrade-tests-worker.yaml

- updated check_bgp_neighbors.sh to load switch admin password from vault
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_
local
surtur
_How were the changes tested and success verified? If schema …

CASMINST-5908-csm-1.4 - updated check_bgp_neighbors.sh to load switch admin password from vault

---

goss-testing/tests/ncn/goss-check-mounts-worker.yaml

On argo workflow for worker rebuild, the ncn-upgrade-tests-workers suite is run.  This suite includes a test to check the usage on the following mounts : /var/lib/containerd, /var/lib/kubelet, /run/containerd. The test will fail is the usage is above 75%. Originally this test was meant to check that the mounts exists for post builds. In order to cover the post build and the rebuild cases, the usage limit needs to be increase to 95%.
What was seen on loki [CASMTRIAGE-4987](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4987) was that the usage for /var/lib/containerd was above 75% and the rebuild workflow final health checks would continue to retry. This check may eventually need to become an alert, but at this point the test needs to be able to handle both post build and rebuild. …

CASMPET-6345 1.4 : Update goss test to handle post build and rebuild cases for worker mount usage

---

goss-testing/suites/ncn-upgrade-tests-storage.yaml

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_
_How were the changes tested and success verified? If schema changes were …

CASMINST-6078 remove reference of a deleted test

---

goss-testing/scripts/check_bgp_neighbors_established.sh

bug/casmtriage-5066 - update BGP test to be more dynamic for different versions of vault
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_ yes
CASMTRIAGE-5066
baldar
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_yes
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?yes
- Were continuous …

bug/casmtriage-5066 - update BGP test to be more dynamic for different versions of vault

---

goss-testing/scripts/check_bgp_neighbors_established.sh

bug/casmtriage-5066 - update BGP test to be more dynamic for different versions of vault
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_ yes
CASMTRIAGE-5066
baldar
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_yes
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?yes
- Were continuous …

bug/casmtriage-5066-csm-1.4 - update BGP test to be more dynamic for different versions of vault

---

goss-testing/automated/run-ncn-tests.sh
goss-testing/scripts/check_bgp_neighbors_established.sh
goss-testing/scripts/check_interface_mac_matches_bond.sh
goss-testing/scripts/k8s_kyverno_polr_list.sh

Fix shellcheck errors

---

goss-testing/scripts/postgresql_backups_check.sh

Augment the postgres backup goss test to check to see if the logical backup cronjobs exist.. The operator should re-create the logical backup cronjob if they are missing, but since this is fundamental to the job running and the artifact getting uploaded to s3, adding this to the initial part of the test seemed valuable.
* Resolves [CASMPET-6422](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6422)
Augment postgres backup goss test to also check for cronjob
* Merge with/before/after NA
* Virtual Shasta V2 (dorian)
* Operator has been running for >10 min, but some postgresql resource have not - so cannot guarantee the cronjob will be there (test-postgres running for 1 minute)
``` …
```

CASMPET-6422-1.5 : Augment postgres backup goss test to also check for cronjob

---

goss-testing/scripts/check_bgp_neighbors_established.sh

Change bgp test when run after worker rebuild to only check that worker.
* https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5164
* `surtur`
```
ncn-w003:~ # TARGET_NCN=ncn-w003 GOSS_BASE=/opt/cray/tests/install/ncn SW_ADMIN_PASSWORD='!nitial0' /opt/cray/tests/install/ncn/scripts/check_bgp_neighbors_established_brad.sh
NAME      DATA   AGE
metallb   1      3d5h
CAN
Running: canu validate network bgp --verbose --network all --password XXXXXXXX
PASS
```
Was a fresh Install tested? N
Was an Upgrade tested?      N - N/A
Was a Downgrade tested?     N - N/A
If schema changes were part of this change, how were those handled in your upgrade/downgrade testing? N/A
Low
* Nothing

Change bgp test to test only the worker being rebuilt (CASMTRIAGE-5164)

---

goss-testing/scripts/check_bios_firmware_versions.sh

While here, collapse some redundant logic and clean up extra whitespace.
* Resolves CASMINST-6210, CASMINST-6138
* `surtur`
Ran the script manually on surtur, which has a mix of old and updated firmware/bios.  Observed expected output.
N/A

CASMINST-6210, CASMINST-6138: update expected fw/bios versions
