Cray-HPE/csm-testing

- goss-testing/scripts/ceph-service-status.sh
Fixes to logic issue with the ceph service check
Fixes the pdsh known host issue so the goss check doesn't put add an invalid entry
* Resolves casminst-3469
* craystack
This is a service check.  The testing was validating the results against the known state of ceph
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? n/a
- Were continuous integration tests run? If not, why? n/a
- Was upgrade tested? If not, why? n/a
- Was downgrade tested? If not, why? n/a
- Were new tests (or test issues/Jiras) created for this change? n/a
n/a
> Casminst 3469 master

- goss-testing/scripts/postgresql_backups_check.sh
During the csm 1.2 upgrade, cronjobs may get re-created because of too many failed attempts to start.
Postgresql cronjob based backup are expected to exist 24hr after the cluster is created. This window needs to be based on when the cronjobs were created (or re-created in the case of the upgrade) and not when the cluster was created.
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix? Yes
* Resolves [CASMINST-4030](issue link)
* Change will also be needed in `release/csm-1.2`
* Merge with/before/after NA
vshasta
drax 
Verified on drax that the script passes as expected.  Some of the postgresql cronjobs had been re-created as part of the upgrade (but not all)
```
ncn-m001:~ # …
```
> CASMINST-4030 master : TESTS - Kubernetes Postgresql Check that Automated Backups are Working

- goss-testing/tests/common/goss-switch-bgp-neighbor-aruba-or-mellanox.yaml
BGP test now looks to see if the `customer management` network is configured in metallb.  If it is, CANU BGP test will run across all VRFS, if it's not it will only run the BGP test on the default VRF.  
CASMINST-4000
Drax 1.0
Hela 1.2
Ran Goss test.  Both tests were successful.
> CASMINST-4000

- goss-testing/tests/common/goss-network-interfaces.yaml
Adjusts a test to ignore `bond0.can0` as it is now optional.
* Resolves CASMINST-4196
* Relates to CASMINST-4195
* Relates to #222 
* `wasp`
```
ncn-m001:~ # export GOSS_BASE=/opt/cray/tests/install/ncn/
ncn-m001:~ # export GOSS_FILE=/opt/cray/tests/install/ncn/tests/goss-network-interfaces.yaml
ncn-m001:~ # goss --vars /opt/cray/tests/install/ncn/vars/variables-ncn.yaml validate
....
Total Duration: 0.014s
Count: 4, Failed: 0, Skipped: 0
ncn-m001:~ # echo $?
0
ncn-m001:~ #
```
Low
> CASMINST-4196 adjust vlan test to ignore options bond0.can0 interface

- goss-testing/scripts/check_clock_skew.sh
Wraps the existing check in a loop that tries three times.
* Resolves CASMINST-4176
- `redbull`
- `fanta`
```
ncn-m001:~/jsalmela # ./!$
./test
Checking clock skew...attempt 1 of 3...
Epoch seconds by node (allowing 1 seconds of drift):
ncn-s001: 1646746048
ncn-s002: 1646746048
ncn-s003: 1646746048
ncn-s004: 1646746048
ncn-m001: 1646746048
ncn-m002: 1646746048
ncn-m003: 1646746048
ncn-w001: 1646746048
ncn-w002: 1646746049
ncn-w004: 1646746049
ncn-w003: 1646746049
Checking clock skew...attempt 2 of 3...
Epoch seconds by node (allowing 1 seconds of drift):
ncn-s001: 1646746059
ncn-s003: 1646746059
ncn-s002: 1646746059
ncn-s004: 1646746059
ncn-m001: 1646746059
ncn-m002: 1646746059
ncn-m003: 1646746059
ncn-w001: 1646746059
ncn-w002: …
```
> CASMINST-4176 retry skew check three times to reduce false positives

- goss-testing/scripts/check_static_routes.sh
- goss-testing/tests/ncn/goss-boot-parameter-check-no-wipe.yaml
- goss-testing/tests/ncn/goss-cfs-state-reporter.yaml
- goss-testing/tests/ncn/goss-check-static-routes.yaml
- goss-testing/tests/ncn/goss-k8s-etcd-cluster-balance.yaml
- goss-testing/tests/ncn/goss-k8s-etcd-database-health.yaml
Debugging goss test failures is a big pain point. Logging alleviates this significantly.
The logging feature has already merged and no problems have been found with it (the mismatched quote typo went in with the same PR, but was a commit unrelated to the logging). This ticket just enables logging for 5 additional tests.
* goss-boot-parameter-check-no-wipe
* goss-cfs-state-reporter
* goss-check-static-routes
* goss-k8s-etcd-cluster-balance
* goss-k8s-etcd-database-health
The script for the check-static-routes test was also modified so that it does not print out the API token by default, as I felt this was something customers may not want being written into a test log file. Instead I made that available if the test script is manually run using a new flag.
Similar to …
> CASMINST-4222: Enable logging for 5 tests

- goss-testing/tests/common/goss-interface-has-ip.yaml
Adjusts a test to ignore `bond0.can0` as it is now optional.
* Resolves CASMINST-4195
* Relates to CASMINST-4196
* Relates to #222 
* `wasp`
```
ncn-m001:~ # export GOSS_BASE=/opt/cray/tests/install/ncn/
ncn-m001:~ # export GOSS_FILE=/opt/cray/tests/install/ncn/tests/goss-interface-has-ip.yaml
ncn-m001:~ # goss --vars /opt/cray/tests/install/ncn/vars/variables-ncn.yaml validate
....
Total Duration: 0.013s
Count: 4, Failed: 0, Skipped: 0
ncn-m001:~ #
```
Low
> CASMINST-4195 adjust ip test to ignore options bond0.can0 interface

- goss-testing/tests/common/goss-interface-has-ip.yaml
Adjusts the bond IP test to use regex for detecting an IP and then echoing PASS to STDOUT.
CASMINST-4195
* `hela`
`/opt/cray/tests/install/ncn/automated/ncn-healthcheck`
Low.
> CASMINST-4195 adjust ip test to use regex and check for PASS

- goss-testing/tests/ncn/goss-k8s-monitoring-url.yaml
- goss-testing/tests/ncn/goss-k8s-storageclass.yaml
- goss-testing/tests/ncn/goss-k8s-trustedcerts-configmaps-exist.yaml
- goss-testing/tests/ncn/goss-k8s-verify-cluster.yaml
* goss-k8s-monitoring-url.yaml
* goss-k8s-storageclass.yaml
* goss-k8s-trustedcerts-configmaps-exist.yaml
* goss-k8s-verify-cluster.yaml
None
```
ncn-m001:/tmp/zz # GOSS_BASE=/opt/cray/tests/install/ncn goss --vars /opt/cray/tests/install/ncn/vars/variables-ncn.yaml -g ./goss-k8s-monitoring-url.yaml v
.
Total Duration: 0.731s
```
```
ncn-m001:/tmp/zz # cat /opt/cray/tests/install/logs/goss-k8s-monitoring-url/20220314_010752_002495453_3488775.log
log_run argument(s): -l goss-k8s-monitoring-url
Executable: '/opt/cray/tests/install/ncn/scripts/monitoring_check.sh'
No arguments to executable …
```
> CASMINST-4233: Enable logging for 4 more tests

- goss-testing/tests/common/goss-command-available.yaml
- goss-testing/tests/ncn/goss-k8s-cray-cli-configured.yaml
- goss-testing/tests/ncn/goss-k8s-ipxe-pod-running.yaml
- goss-testing/tests/ncn/goss-k8s-kea-pod-running.yaml
* goss-command-available.yaml
* goss-k8s-cray-cli-configured.yaml
* goss-k8s-ipxe-pod-running.yaml
* goss-k8s-kea-pod-running.yaml
None
```
ncn-m001:/tmp/zz # GOSS_BASE=/opt/cray/tests/install/ncn goss --vars ./variables-ncn.yaml -g ./goss-command-available.yaml v
..
Total Duration: 1.238s
```
```
ncn-m001:/tmp/zz # cat /opt/cray/tests/install/logs/command_available_*/*
log_run argument(s): -l command_available_0_kubectl_version_client
Executable: 'kubectl'
2 argument(s) to executable: 'version' '--client'
###########################################################################
Client Version: version.Info{Major:"1", Minor:"20", …
```
> CASMINST-4229: Enable logging for 4 upgrade preflight tests

- goss-testing/tests/ncn/goss-dedicated-drive-worker.yaml
- goss-testing/tests/ncn/goss-etcdlvm-drive-master.yaml
- goss-testing/tests/ncn/goss-lvm-drives-storage.yaml
- goss-testing/vars/variables-ncn.yaml
Three different tests are used to validate that LVM labels exist on devices on master nodes, storage nodes, and worker nodes. However, the check being done is essentially the same, with different values being hard-coded into each test. This PR moves those values into the NCN variable file, simplifying each of the three tests in the process.
In addition, logging is enabled for the tests, and a check on the output of the command is added (rather than purely going by the exit code).
None
On hela I ran all 3 tests:
```
ncn-w002:/tmp/zz # GOSS_BASE=/opt/cray/tests/install/ncn goss --vars ./variables-ncn.yaml -g ./goss-dedicated-drive-worker.yaml v
......
Total Duration: 0.025s
Count: 6, Failed: 0, Skipped: 0
```
```
ncn-w002:/tmp/zz # cat …
```
> CASMINST-4226: Simplify & enable logging of LVM label tests

- goss-testing/tests/common/goss-ceph-csi-k8s-requirements.yaml
- goss-testing/tests/ncn/goss-ceph-storage-config-files.yaml
- goss-testing/tests/ncn/goss-ceph-storage-images.yaml
- goss-testing/tests/ncn/goss-rgw-health.yaml
This PR enables logging for the following 4 storage tests:
* goss-ceph-csi-k8s-requirements.yaml
* goss-ceph-storage-config-files.yaml
* goss-ceph-storage-images.yaml
* goss-rgw-health.yaml
The tests themselves were not altered.
None
I ran the updated tests on hela:
```
ncn-s001:/tmp/zz # GOSS_BASE=/opt/cray/tests/install/ncn goss --vars ./variables-ncn.yaml -g ./goss-ceph-csi-k8s-requirements.yaml v
..........
Total Duration: 0.274s
Count: 10, Failed: 0, Skipped: 0
```
```
ncn-s001:/tmp/zz # cat /opt/cray/tests/install/logs/k8s_cm_*/* /opt/cray/tests/install/logs/k8s_secret_csi*/*
log_run argument(s): -l k8s_cm_ceph-csi-config
Executable: '/usr/bin/kubectl'
3 argument(s) to executable: 'get' 'configmap' 'ceph-csi-config'
#################################################################### …
```
> CASMINST-4228: Enable logging for 4 storage tests

- goss-testing/tests/ncn/goss-k8s-postgres-backups.yaml
- goss-testing/tests/ncn/goss-k8s-postgres-clusters-running.yaml
- goss-testing/tests/ncn/goss-k8s-postgres-leader.yaml
- goss-testing/tests/ncn/goss-k8s-postgres-pods-running.yaml
This PR enables logging for the following 4 postgres tests:
* goss-k8s-postgres-backups.yaml
* goss-k8s-postgres-clusters-running.yaml
* goss-k8s-postgres-leader.yaml
* goss-k8s-postgres-pods-running.yaml
No changes were made to the tests themselves.
None
I executed all 4 updated tests on hela.
```
ncn-m001:/tmp/zz # GOSS_BASE=/opt/cray/tests/install/ncn goss -g ./goss-k8s-postgres-backups.yaml v
..
Total Duration: 9.464s
```
```
ncn-m001:/tmp/zz # cat /opt/cray/tests/install/logs/k8s_postgresql_backups_check/20220313_185829_878096271_3281397.log
log_run argument(s): -l k8s_postgresql_backups_check
Executable: '/opt/cray/tests/install/ncn/scripts/postgresql_backups_check.sh'
No arguments to executable …
```
> CASMINST-4227: Enable logging for 4 postgres tests

- goss-testing/tests/ncn/goss-cray-service-etcd-health-check.yaml
- goss-testing/tests/ncn/goss-k8s-certmanager-certs-ready.yaml
- goss-testing/tests/ncn/goss-k8s-certmanager-issuers-ready.yaml
- goss-testing/tests/ncn/goss-k8s-istio-pod-containers-running.yaml
- goss-testing/tests/ncn/goss-k8s-istio-pods-running.yaml
* goss-cray-service-etcd-health-check.yaml
* goss-k8s-certmanager-certs-ready.yaml
* goss-k8s-certmanager-issuers-ready.yaml
* goss-k8s-istio-pod-containers-running.yaml
* goss-k8s-istio-pods-running.yaml
None
```
ncn-m001:/tmp/zz # GOSS_BASE=/opt/cray/tests/install/ncn goss --vars /opt/cray/tests/install/ncn/vars/variables-ncn.yaml -g ./goss-cray-service-etcd-health-check.yaml v
.
Total Duration: 18.223s
```
```
ncn-m001:/tmp/zz # cat /opt/cray/tests/install/logs/etcd_database_health/20220311_182411_930975914_1315099.log
log_run argument(s): -l etcd_database_health
Executable: '/opt/cray/tests/install/ncn/scripts/etcd_database_health.sh'
No …
```
> CASMINST-4232: Enable logging for 5 tests

- goss-testing/tests/ncn/goss-k8s-console-services.yaml
- goss-testing/tests/ncn/goss-k8s-etcd-members.yaml
- goss-testing/tests/ncn/goss-k8s-etcd-service.yaml
- goss-testing/tests/ncn/goss-k8s-nexus-can-pull.yaml
- goss-testing/tests/ncn/goss-k8s-sealed-secret-key.yaml
* goss-k8s-console-services.yaml
* goss-k8s-etcd-members.yaml
* goss-k8s-etcd-service.yaml
* goss-k8s-nexus-can-pull.yaml
* goss-k8s-sealed-secret-key.yaml
None
```
ncn-m001:/tmp/zz # GOSS_BASE=/opt/cray/tests/install/ncn goss --vars /opt/cray/tests/install/ncn/vars/variables-ncn.yaml -g ./goss-k8s-console-services.yaml v
.
Total Duration: 3.836s
```
```
ncn-m001:/tmp/zz # cat /opt/cray/tests/install/logs/k8s_service_console_running/20220314_013341_049839698_3503740.log
log_run argument(s): -l k8s_service_console_running
Executable: '/opt/cray/tests/install/ncn/scripts/python/console_verify_services.py'
No arguments to executable …
```
> CASMINST-4235: Enable logging for 5 tests

- goss-testing/tests/common/goss-network-interfaces.yaml
- goss-testing/tests/ncn/goss-spire-healthcheck.yaml
- goss-testing/tests/ncn/goss-spire-verify-api-fetch-jwt.yaml
- goss-testing/tests/ncn/goss-spire-verify-pods.yaml
* goss-network-interfaces.yaml
* goss-spire-healthcheck.yaml
* goss-spire-verify-api-fetch-jwt.yaml
* goss-spire-verify-pods.yaml
None
```
ncn-w002:/tmp/zz # GOSS_BASE=/opt/cray/tests/install/ncn goss --vars /opt/cray/tests/install/ncn/vars/variables-ncn.yaml -g ./goss-network-interfaces.yaml v
....
Total Duration: 0.028s
Count: 4, Failed: 0, Skipped: 0
```
```
ncn-w002:/tmp/zz # cat /opt/cray/tests/install/logs/interface_*/20220314_012242_01*.log
log_run argument(s): -l interface_bond0.can0
Executable: 'ip'
4 argument(s) to executable: 'link' 'show' 'dev' 'bond0.can0'
###########################################################################
7: bond0.can0@bond0: …
```
> CASMINST-4234: Enable logging for 4 tests

- goss-testing/suites/ncn-afterpitreboot-kubernetes-tests-worker.yaml
- goss-testing/suites/ncn-kubernetes-tests-master.yaml
- goss-testing/suites/ncn-kubernetes-tests-worker.yaml
Call load balancer test after pit is rebooted, and services are fully deployed.
* Resolves [CASMINST-4250](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4250)
N/A -- no change to test, just moving to different suite
N/A
N/A
Low
> Move loadbalancer test to suite after pit reboot

- goss-testing/scripts/check_clock_skew.sh
- goss-testing/tests/ncn/goss-check-clock-skew.yaml
Adds SSH options to allow re-use of the connection, allowing for faster checks of time.
* Resolves CASMINST-4413 for 1.2
* 
* `#redbull`
* `#surtur`
Ran the script with `time` and verified it worked.  It usually clocked in around 1.3 seconds, which is fine for allowing 1 second of drift.
Low
> CASMINST-4413 make ssh connections faster for clock skew test

- goss-testing/scripts/check_clock_skew.sh
- goss-testing/tests/ncn/goss-check-clock-skew.yaml
This minor linting PR is included in the master branch PR for CASMINST-4413 (https://github.com/Cray-HPE/csm-testing/pull/289), but did not make it into the 1.2 PR for that ticket. So this PR is to pull in these minor fixes.
None of them are code changes. Just linting of comments, indentation, and description text.
* CASMINST-4413
* https://github.com/Cray-HPE/csm-testing/pull/289
N/A
Negligible.
> CASMINST-4529: Remove unmatched quote; minor linting; make docs link release-agnostic

- goss-testing/scripts/ceph-service-status.sh
The new version of podman/ceph changes the syntax of how they refer to osds.
went from osd.# to osd-#
* Resolves CASMTRIAGE-3686
* surtur
Debugged the script in place on surtur
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?
> Fixing ceph service check

- Jenkinsfile.github
`goss-servers` was not being published due to a recent change in csm-shared-library (https://github.com/Cray-HPE/csm-shared-library/pull/36) which requires the Component field to match the RPM name.
> CSM-shared-library changed

- goss-testing/suites/ncn-upgrade-preflight-tests.yaml
- goss-testing/tests/ncn/goss-k8s-nexus-space.yaml
This adds in a goss test for a check that there will be enough free space for in the nexus-data pvc for an upgrade. The current size requirements is 150 GiB, this is an estimate and may change with more data found.
* Works on [CASMPET-5737](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5737)
* Future work required by [CASMPET-5737](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5737)
* Documentation changes required in [CASMPET-5737](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5737)
*  mug
Tested by running the goss test on mug and changing the amount of free space required.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? y
No
> CASMPET-5737: Add in nexus free space check

- csm-testing.spec
- goss-testing/automated/livecd-preflight-checks
- goss-testing/automated/livecd-provisioning-checks
- goss-testing/automated/ncn-healthcheck
- goss-testing/automated/ncn-healthcheck-master
- goss-testing/automated/ncn-healthcheck-storage
- goss-testing/automated/ncn-healthcheck-worker
- goss-testing/automated/ncn-kubernetes-checks
- goss-testing/automated/ncn-postgres-tests
- goss-testing/automated/ncn-preflight-checks
- goss-testing/automated/ncn-smoke-tests
- goss-testing/automated/ncn-spire-healthchecks
- goss-testing/automated/ncn-storage-checks
- goss-testing/automated/run-ncn-tests.sh
- goss-testing/tests/common/goss-k8s-nodes-age-valid.yaml
- goss-testing/tests/common/goss-k8s-nodes-joined-cluster.yaml
- goss-testing/vars/variables-common.yaml
- goss-testing/vars/variables-livecd.yaml
- goss-testing/vars/variables-ncn.yaml
- start-goss-servers.sh
* Create common function to determine if script is running on the PIT node; update other scripts to call it.
* Create common function to generate list of NCNs; update other scripts to call it.
* Update goss-k8s-nodes-age-valid and goss-k8s-nodes-joined-cluster tests so they realize ncn-m001 is not in the cluster if they are running on the PIT node.
* Update value of kubectl variable for the PIT node
* Create common goss variable file for variables with same value between PIT and NCN; Modify RPM builder so that it generates NCN/PIT variable files by combining common file with PIT/NCN file.
* Moved a couple of common functions into the common function library.
* General linting and cleanup to make the scripts more consistent.
This ticket began just as a fix to a problem being seen on the …
> CASMINST-5025: Create more shared functions for automated scripts; prove methods for determing NCN lists

- goss-testing/automated/ncn-healthcheck-master
A typo in the ncn-healthcheck-master script meant that it was calling the get_ncns function with an invalid argument ("--master" instead of "--masters"). This PR fixes that. 
I also grepped all of the other files and verified that none of them were using invalid arguments with this function.
Injected by CASMINST-5025.
I tested the updated script on surtur and verified that it now works properly.
One character change. Low risk.
> CASMINST-5129: Fix typo in ncn-healthcheck-master script

- start-goss-servers.sh
The only new failure path introduced that could cause the build issue reported in CASMINST-5124 is if there was a failure creating the temporary variable file during the build. This works fine on live systems, but not during the NCN image build. I think it is likely because csm-testing is not installed during the image build, only goss-servers. Previously this did not generate a fatal error -- it just started up the goss server endpoints even though it wasn't able to find the list of NCNs in /etc/hosts. And that didn't cause problems because the image build doesn't actually try to use any of those endpoints -- it just wants to make sure that the service is able to start.
This PR basically just changes it so that this is not a fatal error to the goss service. Instead it will sleep and …
> CASMINST-5124: Do not fail to start goss-servers if there are errors generating variable files

- goss-testing/automated/livecd-preflight-checks
- goss-testing/automated/livecd-provisioning-checks
- goss-testing/automated/print_goss_json_results
- goss-testing/automated/run-ncn-tests.sh
A few of the Goss automated scripts use Bash scripting and a lot of jq commands to parse the results and display them. This is very slow and can take longer than the tests themselves, more than doubling the time of the script execution.
This PR creates a Python script which replaces that code. The script makes a GET request to a Goss endpoint, or reads Goss JSON results from stdin (or from a file). Either way, it then parses the JSON results and presents them in the same way that the current scripts do. Just much faster (see testing section for details).
[CASMINST-5159](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5159) is phase 1 of a multi-part plan. The next stage is [CASMINST-5161](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5161), to modify our scripts which make …
> CASMINST-5159: Speed up Goss test result reporting

- goss-testing/scripts/etcd_database_health.sh
- goss-testing/scripts/etcd_health_check.sh
Adding the container (-c etcd) when exec'ing into the etcd pods in goss tests.
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix? bug fix
* Resolves [CASMPET-5838](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5838) for goss test, docs which are in progress
* Change will also be needed in NA (only needed for CSM 1.3 and beyond)
drax
* `drax`
Ran goss test to verify no regressions in the fix.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? NA
- Were continuous …
> CASMPET-5838-1.3 : Break/Fix: Etcd health checks failing - need to specify etcd container

- csm-testing.spec
- goss-testing/automated/ncn-healthcheck-master
- goss-testing/automated/ncn-healthcheck-storage
- goss-testing/automated/ncn-healthcheck-worker
- goss-testing/automated/ncn-kubernetes-checks
- goss-testing/automated/ncn-preflight-checks
- goss-testing/automated/ncn-smoke-tests
- goss-testing/automated/ncn-spire-healthchecks
- goss-testing/automated/ncn-storage-checks
- goss-testing/automated/run-ncn-tests.sh
- goss-testing/dat/goss-servers.cfg
- start-goss-servers.sh
Currently, the various Goss server endpoints and ports are not defined in a central place. The service has a shell script which starts up the endpoints, and there are several automated scripts which do curl calls to the endpoints, but they each have the endpoint names and ports hard-coded into them. Any changes to one will break the other, if they are not kept in sync.
In addition, we currently start Goss server endpoints on NCNs where those tests will never run, because we start every endpoint on every NCNs. But, for example, the worker test endpoints don't really need to be started on the masters or storage nodes. It's not a huge deal that they're running, but it's unnecessary.
This PR corrects both issues by creating a single configuration file which defines all of the endpoints, port …
> CASMINST-5171: Move Goss server endpoint definitions to config file

- goss-testing/scripts/velero_backups_check.sh
- goss-testing/tests/ncn/goss-k8s-velero-no-failed-backups.yaml
The current version of velero has a bug which causes a backup to be created when the backup schedule is created.
On installs, this causes the backup to be run before the service is fully healthy and thus the backup ends up PartiallyFailed.
This removes any such PartiallyFailed backup that were created within 10m of the backup schedule creation time. The test then continues to check for any remaining *Failed backups. Those would still need to be investigated, but the initial PartiallyFailed backup will not longer cause the test to fail and need to be remediated since that particular PartiallyFailed backup(s) will be deleted.
This fix will reduce the install time given it automatically remediates those PartiallyFailed backups that are a result of a velero bug before the test to check for …
> CASMINST-4278-1.3 : AUTOMATION: Find a solution/automated remediation/re-execute failed velero backups

- goss-testing/tests/ncn/goss-spire-bss-metadata-exist.yaml
Update the spire bss test description so that it tells the user to recreate the spire bss job if it fails.
* Resolves [CASMPET-5559](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5559)
* shandy
Validated test still worked properly
- Were continuous integration tests run? If not, why? Y 
- Was upgrade tested? If not, why? N
- Was downgrade tested? If not, why? N
- Were new tests (or test issues/Jiras) created for this change? N
_Are there known issues with these changes? Any other special considerations?_
> CASMPET-5559 Update spire-bss test description

- goss-testing/suites/ncn-healthcheck-master.yaml
- goss-testing/suites/ncn-healthcheck-worker.yaml
- goss-testing/tests/ncn/goss-platform-ca-in-bundle.yaml
- goss-testing/tests/ncn/goss-validate-certifi-version.yaml
Adds tests to validate that the platform CA is included in the ca-bundle.pem and that a new version of certifi has not been installed.
* Resolves [CASMPET-5620](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5620)
* Shandy
Validated that goss tests passed on systems setup correctly and failed when modified.
- Were continuous integration tests run? If not, why? Y
- Was upgrade tested? If not, why? N, new tests.
- Was downgrade tested? If not, why? N, new tests.
- Were new tests (or test issues/Jiras) created for this change? Y
> CASMPET-5620 Add additional TLS tests

- goss-testing/automated/python/goss_suite_urls.py
- goss-testing/automated/python/goss_suites_endpoints_ports.py
- goss-testing/automated/python/lib/common.py
- goss-testing/automated/python/lib/endpoints.py
- goss-testing/automated/python/print_goss_json_results.py
- goss-testing/dat/goss-servers.cfg
Among a number of smaller changes, this PR modifies the automated scripts so that when they are running Goss tests using server endpoints, it runs them in parallel. This allows significant reduction in execution time. Specifically, the combined NCN and Kubernetes health check script went from taking 1m 33s to 44s -- halving the time.
My testing revealed no problems with this, but in case problems are seen on any particular system, I did make the number of parallel threads to be configurable using an environment variable, so even serial execution can be used if needed.
This PR also reverses course on a change made in the Goss server data file format made in a recent PR. I decided it felt safer to specify the port numbers explicitly in the file, rather than have them calculated dynamically. …
> CASMINST-5162: Parallelize execution of remote Goss tests

- goss-testing/automated/python/print_goss_json_results.py
Reviewing the code, I identified a few small mistakes in some of the error paths in the Python scripts. Specifically, sometimes an Exception is needlessly assigned to a variable (no big deal), but a couple of times it ought to be assigned to a variable but is not (which would result in a secondary failure). 
This PR is very limited in scope.
Despite the limited scope of the changes, I ran the updated script on surtur just to make sure no new problems were introduced.
Riskier not to include these fixes.
> CASMINST-5218: Minor bug fixes in Python script error paths

- goss-testing/scripts/check_static_routes.sh
The goss-check-static-routes.yaml failed on w001 on fanta.   The logs from that test run showed this:
```
log_run argument(s): -l check_static_routes
Executable: '/opt/cray/tests/install/ncn/scripts/check_static_routes.sh'
1 argument(s) to executable: '-p'
###########################################################################
INFO: NMN gateway is 10.252.0.1
INFO: HMN gateway is 10.254.0.1
INFO: NMNLB CIDR is 10.92.100.0/24 - route found = true
INFO: NMNLB CIDR is 10.106.0.0/22 - route found = true
INFO: HMNLB CIDR is 10.94.100.0/24 - route found = true
INFO: HMNLB CIDR is 10.107.0.0/22 - route found = true
INFO: MTL CIDR is 10.1.0.0/16 - route found = false
FAIL
###########################################################################
```
The MTL CIDR and NMN gateway look correct …
> CASMINST-5239: Fix occasional failure in goss_check_static_routes test

- goss-testing/automated/python/lib/common.py
- goss-testing/automated/python/lib/endpoints.py
- goss-testing/automated/python/print_goss_json_results.py
- goss-testing/automated/run-ncn-tests.sh
This PR's primary purpose is to have local Goss tests run in parallel alongside the remote Goss tests. My previous changes made the remote tests run in parallel, but the local tests were still run before or after those tests. This PR puts them all into the same parallel execution pool.
Right now this doesn't reap huge performance benefits. However, I noticed some areas of improvement in some of our test scripts that I think I can combine with this change to make some of our automated scripts execute more quickly.
This is a continuation of the various recent Goss testing performance enhancements we've been making. Most notably:
- [CASMINST-5162](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5162)
- [CASMINST-5195](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5195)
- …
> CASMINST-5213: Run local tests in parallel with remote endpoint tests

- goss-testing/scripts/k8s_kyverno_pods_running.sh
- goss-testing/scripts/k8s_kyverno_polr_list.sh
Scripts to validate kyverno configuration.
Tested on drax running csm 1.3
Manually tested the scripts with -p parameter and the logs are as below.
Kyverno pods validation:
ncn-m001:/tmp # ./k8s_kyverno_pods_running.sh -p
PASS
ncn-m001:/tmp #
Kyverno Policy report validation:
ncn-m001:/tmp # ./k8s_kyverno_polr_list.sh -p
Error: There are 54 failures in policy report.
Look into the Kyverno policy management document to address the failures/warnings/errors/skipped
FAIL
ncn-m001:/tmp #
These are standalone scripts used to troubleshoot Kyverno.
> CASMINST-5088: Scripts to validate kyverno configuration.

- goss-testing/scripts/check_bios_firmware_versions.sh
C33 comes with papaya.  Since the BIOS doesn't get upgraded until
later in the install, C33 will not typically be present when this
test runs from the pit node early in an install or upgrade.  As
such, leave the older versions in place as well.
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_
* Resolves MTL-1927
_Are there known issues with these changes? Any other special …
> MTL-1927: bump expected BIOS version

- goss-testing/tests/ncn/goss-k8s-resolve-external-dns.yaml
The original keycloak token generation api call does not handle special character password appropriately, nor emits error when DNS test requirements are not met. The PR fixes both issues.
* Resolves [CASMINST-5224](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5224)
* Change will also be needed in `release/1.3 and release/1.2`
* `mug` (1.2)
* `fanta` (1.3)
Verified that the goss-k8s-resolve-external-dns test now passes with the fix.
- Were the …
> CASMINST-5224: handle special password character and fix exit code

- goss-testing/tests/livecd/goss-artifacts-in-place.yaml
- goss-testing/vars/variables-livecd.yaml
`filesystem.squashfs` has been renamed to `rootfs` so this test needs to be updated to align with that change.
* Resolves CASMTRIAGE-4018
* `#starlord`
Installed RPMs.  Ran both `csi pit validate --livecd-preflight` and `/opt/cray/tests/install/livecd/automated/livecd-preflight-checks`.  Validated that the test no longer failed.
Low.
> CASMTRIAGE-4018 use rootfs instead of the deprecated filesystem.squashfs

- goss-testing/tests/ncn/goss-k8s-nexus-can-pull.yaml
Update nexus test to pull correct pause image.
* Resolves [CASMTRIAGE-4057](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4057)
Tested fix on fanta:
```
ncn-m001:~ # export GOSS_BASE=/opt/cray/tests/install/ncn; goss -g /opt/cray/tests/install/ncn/tests/goss-k8s-nexus-can-pull.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml v
Total Duration: 0.153s
```
* `fanta`
Tested on fanta
Low
> Update pause version for nexus test

- goss-testing/tests/ncn/goss-k8s-nexus-can-pull.yaml
Update nexus test to pull correct pause image.
* Resolves [CASMTRIAGE-4057](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4057)
Tested fix on fanta:
```
ncn-m001:~ # export GOSS_BASE=/opt/cray/tests/install/ncn; goss -g /opt/cray/tests/install/ncn/tests/goss-k8s-nexus-can-pull.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml v
Total Duration: 0.153s
```
* `fanta`
Tested on fanta
Low
> Update pause version for nexus test (CASMTRIAGE-4057)

- goss-testing/suites/ncn-healthcheck-storage.yaml
- goss-testing/suites/ncn-healthcheck-worker.yaml
1.3 backport of https://github.com/Cray-HPE/csm-testing/pull/388
> CASMINST-5311: Run clock skew tests on worker and storage NCNs during CSM health validation

- goss-testing/tests/common/goss-unbound-dns-entries.yaml
- goss-testing/tests/ncn/goss-k8s-nexus-pods-running.yaml
- goss-testing/tests/ncn/goss-k8s-velero-backup-storage-locations-available.yaml
- goss-testing/tests/ncn/goss-k8s-velero-backup-vault-schedule-exists.yaml
- goss-testing/tests/ncn/goss-spire-bss-metadata-exist.yaml
- goss-testing/tests/ncn/goss-unbound-ip.yaml
Add logging (using the existing logrun framework) to 6 additional tests:
* `common/goss-unbound-dns-entries.yaml`
* `ncn/goss-k8s-nexus-pods-running.yaml`
* `ncn/goss-k8s-velero-backup-storage-locations-available.yaml`
* `ncn/goss-k8s-velero-backup-vault-schedule-exists.yaml`
* `ncn/goss-spire-bss-metadata-exist.yaml`
* `ncn/goss-unbound-ip.yaml`
This is a very low risk change, but I will not merge this 1.3 PR until it is approved to be included in the release. If it is not, I'll close this PR and only merge it into main/1.4.
I ran the updated tests on starlord and verified that they ran and logged correctly.
Very low risk. The logrun tool is deliberately transparent, invisibly passing through the input, output, and return code, while logging to a file.
> CASMINST-5312: Enable logging of additional tests

- goss-testing/scripts/k8s_kyverno_pods_running.sh
Fix the typo in the kubectl command noted in this PR comment:
https://github.com/Cray-HPE/csm-testing/pull/378#discussion_r964373353
Very low risk -- the command does not work without correcting this typo.
```text
ncn-m001:~ # running_pods=$(kubectl get poda -n kyverno -o json | jq '[.items[] | select(.metadata.labels.app == "kyverno").status.containerStatuses[0].state.running] | length')
error: the server doesn't have a resource type "poda"
ncn-m001:~ # running_pods=$(kubectl get pods -n kyverno -o json | jq '[.items[]                                                                                          | select(.metadata.labels.app == "kyverno").status.containerStatuses[0].state.ru                                                                                         nning] | …
```
> CASMINST-5316: Fix typo in k8s_kyverno_pods_running.sh

- goss-testing/tests/ncn/goss-boot-parameter-check-no-wipe.yaml
Fix for https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4095 -- point to cray bss command if wipe flag test fails.
* Resolves [CASMTRIAGE-4095](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4095)
Not a functional change
N/A
N/A
Low
> Point to cray bss as alternative to setting wipe flag w/out csi (CASMTRIAGE-4095)

- goss-testing/tests/ncn/goss-unused-drives-on-storage-nodes.yaml
The doc link provided in this test no longer existed. This PR updates it, as well as providing instructions on how to manually run the test.
Associated docs PRs:
https://github.com/Cray-HPE/docs-csm/pull/2498
https://github.com/Cray-HPE/docs-csm/pull/2499
I tested the updated test on surtur:
```text
Failures/Skipped:
Title: Check for unused drives on utility storage nodes
Meta:
desc: This test validates that the Ceph cluster contains the expected number of OSDs based on the hardware type and number of storage nodes.
If the test fails, then see "install/troubleshooting_unused_drives_on_storage_nodes.md" in the CSM documentation for remediation steps.
The test can be executed manually on any master NCN or the first three storage NCNs with the following command: …
```
> CASMINST-5352: Improve description and provide correct doc link for goss-unused-drives-on-storage-nodes test

- goss-testing/scripts/k8s_psp_enabled_check.sh
- goss-testing/tests/ncn/goss-k8s-psp-enabled.yaml
Make the following modifications to the k8s_psp_enabled test:
- Change its Goss name field from "k8s_nodes_ready" to "k8s_psp_enabled"
- Move its checking logic into a separate shell script file (k8s_psp_enabled_check.sh)
- Enhance the checking logic by more carefully checking for command failures and unexpected situations
- Provide additional output when performing the checks, to make it clear what exactly happened
- Enable logging of the test using the logrun tool
Despite that being a long-ish list of changes, fundamentally it is still the same test using the same core logic.
If there is approval, I'll backport this into 1.3 as well. Otherwise it will be 1.4 only.
This is part of an ongoing series of tickets in which I am adding test logging to those tests which still lack it.
I ran the …
> CASMINST-5371: Add logging to k8s_psp_enabled Goss test

- goss-testing/tests/ncn/goss-k8s-precache-images-health.yaml
This simplifies the k8s-precache-images-health test (by removing unnecessary grep and wc commands) and adds logrun logging of the kubectl command being run.
If there is approval, I'll backport this into 1.3 as well. Otherwise it will be 1.4 only.
This is part of a series of tickets I'm using to add logging to the Goss tests which still lack it.
I executed the updated test on rocket and verified that it still worked as expected.
Very low risk. Test still checks the same thing, just in a simpler way. The logging was added using the existing logrun tool.
> CASMINST-5373: Add logging to k8s-precache-images-health test

- goss-testing/scripts/k8s_nodes_ready_check.sh
- goss-testing/tests/ncn/goss-k8s-etcd-endpoint-health.yaml
- goss-testing/tests/ncn/goss-k8s-kea-pod-running.yaml
- goss-testing/tests/ncn/goss-k8s-nodes-ready.yaml
This PR mostly makes improvements to the k8s-nodes-ready Goss test with the following:
- Moves the testing logic into a separate Bash script file
- Makes that checking more careful, precise, and verbose in its output
- Adds logging using the logrun tool
This PR also makes a slightly modification to the k8s_service_kea_running test, enabling it to run with pipefail enabled, so that if any part of its command pipeline fails, the test will fail.
Finally, the PR changes the testlabel field in the goss-k8s-etcd-endpoint-health test, since it was the same as the label for the goss-k8s-etcd-database-health test. This will result in the log files from the tests being more easily linked with the originating test.
If there is approval, I'll backport this into 1.3 as well. Otherwise it will be 1.4 …
> CASMINST-5374: Add logging to k8s-nodes-ready; k8s-kea-pod-running should fail if any subcommand fails

- goss-testing/scripts/python/check_for_unused_drives.py
In goss test "Check for unused drives on utility storage nodes", allow check to pass if #osds / #storage-nodes has no remainder. 
Previously, this check only allowed the following number of osds per storage node based on hardware:
"gigabyte": 12,
"hpe": 8,
"intel": 1 or more
* Resolves [CASMTRIAGE-4185](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4185)
* Change will be backported to  `release/1.3`
* mug
- Tested script to directly on mug. Script runs well 
- Was unable to test goss test that calls this script as that goss test is only run on a pit node
_How were the changes tested and success verified? If …
> CASMTRIAGE-4185 edit number of expected osds in check for unused drives

- goss-testing/scripts/data-validator.py
The boot param test was too restrictive for **initrd**.
backwards compatible: yes
https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4269
* Rocket
No known risks.
> CASMTRIAGE-4269 - less restrictive boot param

- goss-testing/tests/common/goss-bond-members-have-correct-mtu.yaml
- goss-testing/tests/common/goss-services-enabled.yaml
- goss-testing/tests/common/goss-services-running.yaml
- goss-testing/tests/livecd/goss-bmc-check.yaml
- goss-testing/tests/livecd/goss-chrony-config.yaml
- goss-testing/tests/livecd/goss-firmware-bios-baseline.yaml
- goss-testing/vars/variables-livecd.yaml
- goss-testing/vars/variables-ncn.yaml
- Adds conditionals to skip a small subset of tests when a non-metal environment is detected such as vshasta.
- For metal installs, nothing changes besides the addition of a `vshasta: false` variable
- For `vshasta` installs, this value is overridden to `true` so that the irrelevant tests are skipped
Several tests are not applicable in vshasta, so this adds a simple check by checking for 'HPC' in the `/etc/os-release` file, which is not present on the nodes we deploy to GCP.
Using this logic, the tests still run on metal, but are skipped in a vshasta environment
* Partially resolves VSHA-477
* Merge before https://github.com/Cray-HPE/livecd-gcp-infrastructure/pull/163
* vshasta2
* `#redbull`
```
pit:~ # goss -g …
```
> VSHA-477 add conditional check for tests that do not apply to vshasta

- goss-testing/automated/run-ncn-tests.sh
- goss-testing/scripts/python/check_for_unused_drives.py
- goss-testing/tests/common/goss-interface-has-ip.yaml
- goss-testing/tests/common/goss-interfaces-have-same-mac.yaml
- goss-testing/tests/common/goss-ncns-in-dnsmasq-leases.yaml
- goss-testing/tests/common/goss-network-interfaces.yaml
- goss-testing/tests/livecd/goss-net-dhcp-pools-in-dnsmasq_d-are-correctly-defined.yaml
- goss-testing/tests/livecd/goss-rgw-cert-valid.yaml
- goss-testing/tests/ncn/goss-weave-health.yaml
- goss-testing/vars/variables-common.yaml
- start-goss-servers.sh
Add vshasta support to some existing tests by adding a conditional.
Adds a `is_vshasta_node` function.
* Partially resolves VSHA-503
* Works with https://github.com/Cray-HPE/livecd-gcp-infrastructure/pull/174
* `#redbull`
Executed the tests on a vshasta environment and saw the tests were skipped.
The function works on a vshasta pit node:
```
pit:~ # is_vshasta_node ; echo $?
+ [[ -f /etc/google_system ]]
+ return 0
+ echo 0
0
pit:~ #
```
a metal image booted to vshasta:
```
ncn-m002:~ # is_vshasta_node ; echo $?
+ [[ -f /etc/google_system ]]
+ grep --color=auto Google
+ lsblk --noheadings -o vendor
+ return 0
+ echo 0
0
```
and a metal node:
```
redbull-ncn-m001-pit:~ # is_vshasta_node ; echo $?
+ [[ -f …
```
> VSHA-503 modify tests for use on vshasta

- goss-testing/automated/run-ncn-tests.sh
- goss-testing/tests/ncn/goss-ceph-status.yaml
- #414 did not actually create the temporary variables correctly.  This adjusts that.
- required by https://github.com/Cray-HPE/livecd-gcp-infrastructure/pull/174
* Resolves VSHA-503
Ran the weave test, known to fail without the var, and watched it pass.
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?
Low
> VSHA-503 fix tmp vars not creating correctly

- goss-testing/automated/python/lib/common.py
- goss-testing/automated/python/print_goss_json_results.py
This modifies print_goss_json_results.py so that it creates an additional log file, suitable for consumption by grok-exporter. Specifically, this new log file meets the two requirements that the current log files fail to:
1) Its directory name is static, not dynamic (it logs to `/opt/cray/tests/install/logs/grok_exporter/`)
2) Its log entries do not span multiple lines (data that would normally span multiple lines is converted into a JSON string with newlines (if any) escaped).
No existing function of the tool has changed -- only this additional thing added.
- Resolves [CASMINST-5677](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5677)
- Needed as part of epic [CASM-3373](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3373)
I tested this on frigg and verified that it works and …
> CASMINST-5677: print_goss_json_results: Produce log file consumable by grok-exporter

- goss-testing/tests/ncn/goss-k8s-resolve-external-dns.yaml
Update load-balancer ingress path to use for Keycloak interaction, given the master realm admin auth is being requested. This as the CMN LB, specifically the `auth.cmn.*` ingress paths are now supported for master realm administration. 
Use a DNS A record query instead of ping, this to address CAST-31571 as a tangent. 
This should be backward compatible with all releases that included CMN. 
* Resolves [CASMINST-5766](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5766)
* Resolves [CAST-31571](https://jira-pro.its.hpecorp.net:8443/browse/CAST-31571)
* Caused by [CASMSEC-371](https://jira-pro.its.hpecorp.net:8443/browse/CASMSEC-371)
Tested by editing test in place on …
> CASMINST-5766: Use CMN for Keycloak access, use DNS query vs. ping for test

- Jenkinsfile.github
- Makefile
- csm-testing.spec
Build a matrix of distros.
This ensures each distro we build for has matching metadata. The RPMs that were pushed to the SP2 repo had SP3 metadata, which isn't important - but it doesn't line up.
Now adding a new SLES release just involves updating the matrix array.
Relates to: https://github.com/Cray-HPE/csm-testing/pull/424
> MTL-1708 Build matrix of distros

- Jenkinsfile.github
`goss-servers` needs a different name for the `component` field when invoking the csm-shared-library function.
> MTL-1708 Part 2 - Publish `goss-servers`

- goss-testing/automated/python/lib/grok_exporter_logger.py
- goss-testing/automated/python/print_goss_json_results.py
Sumith R B requested that print_goss_json_results not use scientific notation for test durations in the log file consumed by grok exporter. This PR makes that change, and also fixes some small bugs that I found while coding and testing this change.
[CASMINST-5793](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5793)
The change is not large, but the code path is one which is hit a lot, since every test result that is parsed is also logged. However, because of this, it was easy to do extensive testing of this. I did so on wasp. To the end user, there is no change. The only external difference is in the format of the grok exporter log file.
Sumith also tested the new code on mug and verified that it produced logs that could be consumed by grok exporter.
If this is omitted, then not …
> CASMINST-5793: print_goss_json_results: Do not use scientific notation when logging test duration in seconds; minor bug fixes

- goss-testing/tests/ncn/goss-k8s-resolve-external-dns.yaml
Forward port from release/1.3: Use CMN for Keycloak access, use DNS query vs. ping for test
(cherry picked from commit 98eaf915080f6ee3ab08678144d9741af3d1b0fc)
Tested on Wasp (1.4.0-beta.36) by patching test in place on m002, restarting `goss-servers` on m002, and then running `/opt/cray/tests/install/ncn/automated/ncn-k8s-combined-healthcheck` on the PIT. 
See: https://github.com/Cray-HPE/csm-testing/pull/422
> CASMINST-5838: Use CMN for Keycloak access, use DNS query vs. ping for test

- goss-testing/scripts/check_static_routes.sh
While running the "NCNs Have All Required Static Routes" test in the ncn-k8s-combined-healthcheck on baldar, the test failed because baldar has an EX2500 cabinet with no river nodes.  Therefore, no NMN_RVR or HMN_RVR subnets were allocated in SLS.   Additionaly, the test was not checking static routes for the MTN networks.   The test has been changed to first check if the RVR and MTN networks are defined and then only check for the static routes if they are defined.   The test also now added checks for the MNT networks.
* Resolves [CASMINST-5850](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5850)
* `baldar` and `surtur`
Ran the test on balder where there are MTN …
> CASMINST-5850:  Make check_static_routes.sh handle undefined RVR networks and also test MTN networks

- goss-testing/automated/run-ncn-tests.sh
- goss-testing/tests/common/goss-k8s-nodes-master-taint.yaml
If the master NoSchedule taints are not defined, then may pods will be scheduled to the masters nodes when they should only be scheduled on worker nodes.   This is particularly an issue with the sonar-job-watcher CronJob.   That job mounts a volume with a subPath.   As shown in https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4827, this causes kubelet to become very bogged down to the point that pods take a very long time to move from Pending to Running.
Bottom line is that we only want a certain small set of pods to be scheduled on the master nodes.   This test makes sure that the master taints are defined to prevent any other pods from being scheduled on the master nodes.   The test gets run as part of the CSM health checks.
* Resolves …
> CASMINST-5819: Add test to check for taints on master nodes

- goss-testing/scripts/etcd_backups_check.sh
CRUS is being removed from CSM 1.6. Only one Goss test is affected by this -- a script which validates etcd cluster backups. This PR removes the CRUS cluster from the list of clusters being backed up. No other changes.
* Part of the [CRUS removal](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8396) epic.
None -- the change is so limited that the impact is obvious -- the CRUS cluster is no longer included in the checks.
Very low risk, but without this change, this script will always fail.
> CASMINST-5874: Update Goss tests for CRUS removal

- goss-testing/scripts/data-validator.py
`rd.live.overlay.thin` is now set to `0` to prevent the extraneous error messages from printing.
See: https://github.com/Cray-HPE/metal-ipxe/pull/56
> MTL-2085 `rd.live.overlay.thin` is now `0`

- goss-testing/tests/common/goss-bond-members-have-links.yaml
For vShasta installation, a test named `goss-bond-members-have-links`, executed on PIT node during pre-flight check, should be disabled - similar to other bond members pre-flight checks on vShasta.
* Resolves [CASMTRIAGE-4994](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4994)
Applied modified test suite directly on vShasta system. Test which was previously failing is ow skipped.
Low - turning off single test.
> CASMTRIAGE-4994 Turn off goss-bond-members-have-links on vShasta

- goss-testing/suites/ncn-healthcheck-master-single.yaml
- goss-testing/suites/ncn-kubernetes-tests-master.yaml
- goss-testing/suites/ncn-kubernetes-tests-worker.yaml
- goss-testing/tests/common/goss-rgw-cert-valid.yaml
- goss-testing/tests/ncn/goss-bss-basecamp-valid.yaml
- goss-testing/tests/ncn/goss-ceph-status.yaml
- goss-testing/tests/ncn/goss-cfs-state-reporter.yaml
- goss-testing/tests/ncn/goss-check-static-routes.yaml
- goss-testing/tests/ncn/goss-default-gateway-points-to-CMN-gateway.yaml
- goss-testing/tests/ncn/goss-k8s-kea-has-active-dhcp-leases.yaml
- goss-testing/tests/ncn/goss-k8s-monitoring-url.yaml
- goss-testing/tests/ncn/goss-k8s-resolve-external-dns.yaml
- goss-testing/tests/ncn/goss-weave-health.yaml
I took a look at the goss tests that are getting skipped on vshasta during the CI testing.   I found a few that do not need to be skipped anymore.
* goss-rgw-cert-valid.yaml
* goss-ceph-status.yaml
* goss-weave-health.yaml
I am also adding in healthcheck tests to the pipeline in VSHA-541 and that requires a few more tests to be skipped on vshasta.
* goss-bss-basecamp-valid.yaml - the bootparameters are not setup in vshasta
* goss-cfs-state-reporter.yaml - cfs-state-reporter doesn't start up properly on vshasta
* goss-check-static-routes.yaml - there is no ipam configuration in basecamp/bss on vshasta
* goss-default-gateway-points-to-CMN-gateway.yaml - there is no ipam configuration in basecamp/bss on vshasta
* goss-k8s-kea-has-active-dhcp-leases.yaml - there are no BMCs to DHCP and get …
> VSHA-542:  Adjust the goss test skips for vshasta

- goss-testing/scripts/postgresql_backups_check.sh
- goss-testing/tests/ncn/goss-k8s-postgres-backups.yaml
With the latest upstream postgres-operator, we are changing from our home-grown backup solution to the logical-backup solution provided by the operator. 
This change updates the postgresql backup check - for those clusters with logical backups enabled; the test will pass unless the latest logical-backup job has failed or the logical-backup completed but no backup exists in s3.
* Resolves [CASMPET-6283](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6283)
* Merge with/before/after NA
* Virtual Shasta v2 - dorian
* Passes if none of the clusters have enabled logical …
> CASMPET-6283 1.5 : Rework postgres backup goss tests

- goss-testing/automated/python/lib/common.py
- goss-testing/dat/goss-servers.cfg
- start-goss-servers.sh
The `goss-servers` RPM package is currently installed on PIT node and systemd service is configured to start. However, it fails to start due to multiple misconfigurations. This PR is to address misconfigurations, and allow test execution on pit node by querying URL (similar to other nodes).
* Resolves [CASMINST-6080](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6080)
Installed package on vShasta pit node and restarted `goss-server` service. Server came up as expected, tests can now be executed:
pit:~ # curl http://pit:9001/livecd-preflight-tests
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="goss" errors="0" tests="162" failures="3" skipped="27" time="1.543" timestamp="2023-03-14T19:11:00Z">
<testcase name="Command check_interface_ip_bond0.nmn0 …
> CASMINST-6080 Fix goss-server configuration on PIT node

- goss-testing/scripts/check_interface_mac_matches_bond.sh
As pointed out by `shellcheck`, the return code reported to `error` function was from `if` statement, not from original `ip addr show` command. This small change fixes the issue.
> Fix error return code in check_interface_mac_matches_bond

- goss-testing/tests/ncn/goss-cray-tftp-check.yaml
[CASMTRIAGE-5071](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5071) was opened because the cmsdev tftp get file subtest fails when it is run on a master NCN. This was an unforeseen consequence of [CASMCMS-8450](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8450). However, the solution is that this subtest should not be run on master NCNs.
The cmsdev test tool has been updated so that it will skip that subtest when run on masters. And this PR creates a new Goss test to run the cmsdev tftp test on a worker node, and adds that new test to the single worker healthcheck suite (so that it will run on a single worker during NCN health checks).
This will ensure that running cmsdev on master nodes will continue to work, but that this test coverage will not be lost, and will …
> CASMCMS-8473: Run cmsdev tftp test on a single NCN worker during health checks

- goss-testing/tests/ncn/goss-cray-tftp-check.yaml
Jeanne tested that the new tftp Goss test works on vshasta, so this PR enables it to run on vshasta.
- Modifies test created by [CASMCMS-8473](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8473)
Jeanne ran the new test on dorian.
Low risk.
> CASMCMS-8475: Enable tftp cmsdev Goss test on vshasta

- goss-testing/scripts/postgres_clusters_leader.sh
With the latest postgres operator and spilo image upgrade in CSM 1.5 , the logs message has changed somewhat and the test leader check needs to be adjusted
* Resolves [CASMPET-6425](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6425)
* Merge with/before/after TBD
* Virtual Shasta v2 - dorian
Prior to CSM 1.5, the postgres logs contained
```
2023-03-16 18:47:16,660 INFO: no action. I am the leader with the lock
```
But with CSM 1.5, this changed to 
```
2023-03-16 18:47:16,660 INFO: no action. I am (keycloak-postgres-0), the leader with the lock
```
Before the fix
```
cray-nls-postgres's leader's logs do not contain 'i am the leader with the lock'.
cfs-ara-postgres's leader's logs …
```
> CASMPET-6425-1.5 : csm-vshasta-deploy test failure - k8s_postgres_clusters_have_leaders

- goss-testing/scripts/velero_backups_check.sh
Based on the logs, the backup was PartiallyFailed backup was deleted as expected, but the final check still found that it existed - so this is a timing issue.  Added a loop to wait for the backup to be gone from the kubectl perspective. This only look 1-2 seconds when tested on dorian.
* Resolves [CASMPET-6424](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6424)
* Merge with/before/after TBD
* Virtual Shasta v2 (dorian)
Tested that the while loop will indeed wait until the backup resource is gone from the the kubectl perspective
- Were continuous integration tests run? If not, why?
- …
> CASMPET-6424-1.5 : csm-vshasta-deploy test failure : goss-k8s-velero-no-failed-backups

- goss-testing/suites/ncn-healthcheck-master.yaml
- goss-testing/tests/ncn/goss-check-taints.yaml
This adds the goss-check-taints test.   This test runs on master nodes only and checks that the node-role.kubernetes.io/master:NoSchedule taint exists for the node on which the test is running.  This test has been added to the ncn-healthcheck-master.yaml suite to be run anytime NCN healthcheck tests are run on master nodes and it has been added to the  ncn-upgrade-tests-master.yaml suite to be run after each master node is upgraded.
* Resolves [CASMPET-6426](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6426)
* Related to [CASMTRIAGE-5049](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5049)
* `fanta`
* Virtual Shasta - `beau`
Fanta is a system where we recently found that the master taint is missing on m002.   I ran this test on both m002 where it failed and on m003 where …
> CASMPET-6426: Add goss-check-taints test

- goss-testing/scripts/postgres_pods_running.sh
Modify the existing postgres goss test that checks for the number of running pods. Check that this is correct as compared 
to customizations, postgresql cr and/or partonictl list.
This will allow for the test to pass in a small vshasta v2 environment where the cluster may be customized to only run one instance.
* Resolves [CASMPET-6429](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6429)
csm-vshasta-deploy test failure : k8s_postgres_pods_per_cluster
* Merge with/before/after NA
* Virtual Shasta V2 (dorian)
* Fail if override is customizations does not match that …
> CASMPET-6429 1.5 : csm-vshasta-deploy test failure : k8s_postgres_pods_per_cluster

- start-goss-servers.sh
Found that goss-servers doesn't have access to the HOSTNAME env at startup.   This makes sure it is set to run any tests that need to know the current hostname.
* Resolves [CASMINST-6103](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6103)
* `drax`
Tested without the change and verified that goss-servers service fails.   Tested with this change and verified that the goss-servers services is running and I was able to run the ncn-healthcheck-master endpoint.
> CASMINST-6103:  Make sure the HOSTNAME env is set in start-goss-servers.sh

- start-goss-servers.sh
The HOSTNAME var being set in start-goss-servers.sh doesn't handle the hostname of the pit in vshasta because it is just "pit".   I removed the dash before the pit because it is not needed.   It was only there because I borrowed the regex from run-ncn-tests.sh. 
I also split the export from the var definition to match the same thing done in the main branch to satisfy shell-check.
* Resolves [CASMINST-6130](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6130)
* `fanta`
* Virtual Shasta - `cilium`
On both fanta's m002 and cilium's pit node, I started the goss-servers service and made sure that there were no errors.  I also ran `curl http://ncn-m002.hmn:8997/ncn-healthcheck-master` on fanta to make sure the endpoint still works.
> CASMINST-6130: Fix HOSTNAME var in start-goss-servers.sh

- goss-testing/scripts/etcd_backups_check.sh
- goss-testing/tests/ncn/goss-k8s-etcd-backups.yaml
Add grace period in etcd test that checks for backups
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6446
* ashton
```
ncn-m002:~ # bash -x /tmp/foo.sh 2>&1 | grep -e old_enough -e Pass
++ check_ss_old_enough cray-bos
++ old_enough=0
++ old_enough=1
+ old_enough=1
+ result=Pass
+ '[' Pass == Pass ']'
```
Was a fresh Install tested? N
Was an Upgrade tested?      N - N/A
Was a Downgrade tested?     N - N/A
If schema changes were part of this change, how were those handled in your upgrade/downgrade testing? N/A
Low
* Nothing
> Add grace period for etcd statefulsets not old enough for backup

- goss-testing/suites/ncn-healthcheck-master-single.yaml
- goss-testing/suites/ncn-spire-healthchecks.yaml
- goss-testing/tests/ncn/goss-cray-spire-check-key-id-in-jwks.yaml
- goss-testing/tests/ncn/goss-cray-spire-verify-pods.yaml
This adds and updates tests to account for running multiple spire deployments in CSM 1.5.
* Partially Resolves [CASMPET-6447](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6447)
No test environment available.
No testing done.
- Were continuous integration tests run? If not, why? Y
- Was upgrade tested? If not, why? N, no test environment available
- Was downgrade tested? If not, why? N, no test environment available
- Were new tests (or test issues/Jiras) created for this change? Y
No way to test this outside of the CSM 1.5 pipeline. Won't cause issues, but may continue to fail the build.
- [☹️] Testing is appropriate and complete, if applicable
> CASMPET-6447 Update spire tests to handle cray-spire

- goss-testing/automated/run-ncn-tests.sh
- goss-testing/dat/goss-servers.cfg
- goss-testing/suites/ncn-cms-tests.yaml
- goss-testing/suites/ncn-hms-ct-tests.yaml
- goss-testing/tests/ncn/goss-cms-tests.yaml
- goss-testing/tests/ncn/goss-hms-ct-tests.yaml
Add 2 new goss test suites for HMS CT tests and CMS tests. List of tests for each suite is generated dynamically at the moment when goss server starts. Suites are bound to dedicated port numbers `9005` and `9006` on master nodes.
* Resolves [CASMINST-6097](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6097)
Executed vShasta pipeline, which supports overriding of `csm-testing` and `goss-servers` packages:
https://jenkins.algol60.net/blue/organizations/jenkins/Cray-HPE%2Fcsm-vshasta-deploy/detail/feature%2Fhms-cms-tests/34/tests/
Tests were successfully executed and results recorded. From CMS tests, 3 tests failed (`vcs`, `ims` and `bos`). The 2 latter tests failed due to 1 minute timeout expiration, so I have already increased this timeout to 5 minutes. From HMS …
> CASMINST-6097 Add HMS CT tests and CMS service tests

- goss-testing/automated/run-ncn-tests.sh
- goss-testing/dat/goss-servers.cfg
- goss-testing/suites/ncn-cms-tests.yaml
- goss-testing/tests/ncn/goss-cms-tests.yaml
Backport CMS part of https://github.com/Cray-HPE/csm-testing/pull/478 to `release/1.4`.
* Resolves [CASMINST-6097](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6097)
Running a build with `csm-testing` and `goss-servers` packages overridden:
https://jenkins.algol60.net/blue/organizations/jenkins/Cray-HPE%2Fcsm-vshasta-deploy/detail/release%2F1.4/23/pipeline
Low - new functionality for test framework only.
> CASMINST-6097 Add CMS service tests

- goss-testing/tests/ncn/goss-cray-spire-check-key-id-in-jwks.yaml
- goss-testing/tests/ncn/goss-spire-healthcheck.yaml
- goss-testing/tests/ncn/goss-spire-verify-api-fetch-jwt.yaml
The /root/spire path is obsolete and should be changed to it's new path, /var/lib/spire.
* Resolves [CASMPET-6447](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6447)
No environments available to test.
This is another attempt to fix a test being run in the CSM 1.5 test pipeline.
- Were continuous integration tests run? If not, why? Y
- Was upgrade tested? If not, why? N/A
- Was downgrade tested? If not, why? N/A
- Were new tests (or test issues/Jiras) created for this change? N
This may not be the issue, but it should still be updated.
> CASMPET-6447 Update spire socket path.

- .github/dependabot.yml
- Jenkinsfile.github
- Makefile
- csm-testing.spec
This change does a few things.
1. It fixes a race condition in the `matrix` where one axis overrides the other axis' delivery point. We've observed the SP3 build publishing RPMs into the SP4 build on more than one occasion (see https://jenkins.algol60.net/blue/organizations/jenkins/Cray-HPE%2Fcsm-testing/detail/v1.15.43/2/pipeline/105#step-205-log-2). This is often "fixed" by a re-run, but that has no guarantees of working.
1. This lightens the load on Jenkins by restricting the build to a single GCP agent and spawning a container atop that agent for each axis. Right now multiple hosts are requested, this adds needless demand to Jenkins and is slower.
1. This updates the `Makefile` and `csm-testing.spec` to accommodate the above changes
1. Adds `dependabot.yaml` for auto-updating GitHub …
> Fix Jenkins

- goss-testing/scripts/etcd_health_check.sh
Allow for more than the minimum etcd pods, in case we've got one stuck in terminating on a dead worker.
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6507
```
ncn-m002:/opt/cray/tests/install/ncn/scripts # ./etcd_health_check.sh
--- Check that the Correct Number of Pods Running, Check Endpoint Health, Check if Any Alarms are Set ---
PASS                cray-bos: Expected 3 etcd members, got 3 members. Endpoint health check passed. No alarms set.
PASS                cray-bss: Expected 3 etcd members, got 3 members. Endpoint health check passed. No alarms set.
PASS                cray-fas: Expected 3 etcd members, got 3 members. Endpoint health check passed. No alarms set.
PASS              cray-hmnfd: Expected 3 etcd members, got 3 members. Endpoint health check passed. No alarms …
```
> Fix etcd balance test to allow for stuck/dead pods (CASMPET-6507)

- csm-testing.spec
- goss-servers.service
The `goss-servers.service` file is installed with executable permissions which cause extraneous errors to print to console:
This also patches up some systemd handling:
- `StartLimitInterval` is deprecated in favor of `StartLimitIntervalSec`
- Includes `systemd` macros in the RPM spec for goss-servers to enable/replace/remove the service properly when the RPM is installed and/or updated
> CASMINST-6306 Fix perms and update systemd

- goss-testing/tests/ncn/goss-platform-ca-in-bundle.yaml
Sometimes platform-ca-in-bundle goss testing takes longer than 10 seconds. This PR bumps it to 20 seconds.
* Resolves [CASMTRIAGE-5354](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5354)
* Change will also be needed in `release/1.4.1`
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade …
> CASMTRIAGE-5354: increase test timeout to 20 sec

- goss-testing/tests/ncn/goss-rgw-health.yaml
The goss-rgw-health test fails on vshasta because it doesn't have an HMN network.   Adding the vshasta skip to this test.
* Resolves [CASMINST-6342](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6342)
* Virtual Shasta - grog
Ran the preflight checks in prerequisites on grog and verified that this test was skipped.
Low
> CASMINST-6342: Skip goss-rgw-health.yaml on vshasta

- goss-testing/tests/livecd/goss-ipxe-permissions.yaml
`ipxe.efi` is now two files, `ipxe.x86_64.efi` and `ipxe.arm64.efi`.
> MTL-2167 Handle new ipxe files from MTL-2139

- goss-testing/tests/ncn/goss-k8s-non-bitnami-etcd-clusters.yaml
Add test to detect unsupported etcd clusters in CSM 1.5
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6608
Success:
```
ncn-m002:/opt/cray/tests/install/ncn/tests # GOSS_BASE=/opt/cray/tests/install/ncn goss -g /opt/cray/tests/install/ncn/tests/goss-k8s-non-bitnami-etcd-clusters.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml validate
..
Total Duration: 0.181s
```
Failure:
```
ncn-m001:~ # GOSS_BASE=/opt/cray/tests/install/ncn goss -g /opt/cray/tests/install/ncn/tests/goss-k8s-non-bitnami-etcd-clusters.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml validate
.F
Failures/Skipped:
Title: Verify Etcd Clusters have been migrated to bitmami helm chart
Meta:
desc: Verifies Etcd clusters have been migrated to a supported version …
```
> Add test to detect etcd clusters not converted to bitnami chart

- goss-testing/tests/ncn/goss-k8s-ipxe-pod-running.yaml
In CSM 1.5, cray-ipxe now has two pods -- one which builds x86-64 binaries, and one which builds aarch64. The labels of these pods are both different from the previous iPXE pod label, which is causing a Goss test to fail. This test is run to ensure that NCN boots will work, so in that context we are only concerned with the x86-64 iPXE pod. The cmsdev test tool already includes more complete test coverage of iPXE, including the new aarch64 binaries, so it doesn't make sense to duplicate that here.
This modifies the test to use the correct label for the x86-64 pod.
* Resolves [CASMTRIAGE-5616](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5616)
* Related to the changes made to cmsdev with [CASMCMS-8504](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8504)
I tested the updated …
> CASMTRIAGE-5616: Update iPXE check to look for the x86-64 iPXE pod specifically

- goss-testing/suites/ncn-patch-upgrade-preflight-tests.yaml
- goss-testing/suites/ncn-post-csm-service-upgrade-tests.yaml
- goss-testing/suites/ncn-upgrade-preflight-tests.yaml
- goss-testing/suites/ncn-upgrade-tests-master.yaml
- goss-testing/tests/ncn/goss-k8s-ipxe-pod-running-pre-upgrade.yaml
It turns out that we can no longer use the same iPXE test for all places where it was previously being run. It worked before because the iPXE deployment didn't have fundamental changes from one CSM version to another. However, that is not true from CSM 1.4 to CSM 1.5. Therefore we need to run the old-style check when doing pre-service-upgrade checks, and the new-style check when doing checks after the CSM services have been upgraded.
This PR splits off a pre-upgrade iPXE test, and modifies the appropriate test suite to call it. This PR also adds comments to several suites explaining when they are run (specifically in relation to CSM upgrades), to hopefully make this easier to navigate in the future.
Note that this will have to be modified again to handle upgrades where both the starting …
> CASMTRIAGE-5630: Split iPXE check into two tests

- goss-testing/tests/ncn/goss-k8s-pods-ips-in-nmn-pool.yaml
Cleanup goss-k8s-pods-ips-in-nmn-pool.yaml test, parse K8S 1.22 output correct and discover NMN subnet from SLS.
* https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5638
* https://jira-pro.it.hpe.com:8443/browse/CASMINST-3769
drax:
```
ncn-m001:/opt/cray/tests/install/ncn # export GOSS_BASE=/opt/cray/tests/install/ncn; goss -g /opt/cray/tests/install/ncn/tests/goss-k8s-pods-ips-in-nmn-pool-brad.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml validate
..
Total Duration: 0.747s
```
Was a fresh Install tested? N
Was an Upgrade tested?      N - N/A
Was a Downgrade tested?     N - N/A
If schema changes were part of this change, how were those handled in your upgrade/downgrade testing? N/A
Low
* Nothing
> Fixes for goss-k8s-pods-ips-in-nmn-pool.yaml in CSM 1.5 (CASMTRIAGE-5638)

- goss-testing/tests/ncn/goss-k8s-istio-pods-running.yaml
During istio upgrade, there will be short-lived completed wait-for pods that will cause an istio goss test to fail as it only expects pods with running state. This PR amends the test with either Running or Completed pods.
* Resolves [CASMTRIAGE-5580](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5580)
* `drax`
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_
- Were continuous …
> CASMTRIAGE-5580: check for completed pods

- goss-testing/tests/ncn/goss-cms-tests.yaml
- goss-testing/tests/ncn/goss-cray-tftp-check.yaml
(cherry picked from commit 0374b80a233aed9d3f913316283a98d9d4ec86d2)
Limited 1.4.2 backport of this PR:
https://github.com/Cray-HPE/csm-testing/pull/509
Specifically, this just adds some troubleshooting information to the CMS Goss test files.
> CASMINST-6538: Add troubleshooting info to CMS test files

- goss-testing/scripts/check_goss_k8s_pods_ips_in_nmn_pool.sh
- goss-testing/tests/ncn/goss-k8s-pods-ips-in-nmn-pool.yaml
Enhance goss-k8s-pods-ips-in-nmn-pool.yaml test to attempt to find sls file on filesystem if sls not available, as well as use nmap to determine if IP is in subnet range.
* https://jira-pro.it.hpe.com:8443/browse/CASMINST-6527
Drax:
```
ncn-m001:~/brad # export GOSS_BASE=/opt/cray/tests/install/ncn; goss -g /opt/cray/tests/install/ncn/tests/goss-k8s-pods-ips-in-nmn-pool-brad.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml validate
..
Total Duration: 1.660s
```
```
ncn-m001:~/brad # ./check_goss_k8s_pods_ips_in_nmn_pool.sh
Successfully called sls search networks...
PASS: All K8S pod IPs are in the NMN Bootstrap DNCP Subnet
```
```
ncn-m001:~/brad # ./check_goss_k8s_pods_ips_in_nmn_pool.sh
Failed to talk to sls, looking for sls_input_file.json …
```
> Fix nmn pool test to attempt to find input file if sls not up yet (CASMINST-6527)

- goss-testing/automated/ncn-post-csm-service-upgrade-tests
- goss-testing/automated/ncn-upgrade-preflight-tests
- goss-testing/automated/ncn-upgrade-tests-master
- goss-testing/automated/ncn-upgrade-tests-storage
- goss-testing/automated/ncn-upgrade-tests-worker
- goss-testing/scripts/check_ipxe_x86_64_pod_is_running.sh
- goss-testing/tests/ncn/goss-k8s-ipxe-pod-running-pre-upgrade.yaml
This PR makes the following changes/additions:
* Creates a new iPXE check script that will pass if the CSM 1.4 style iPXE pod is running or if the CSM 1.5 style x86-64 iPXE pod is running (it will not pass if only the aarch64 pod is running, because that won't work for NCN boots).
* Modifies the iPXE test run during stage 0 of CSM upgrades to use this new script. This is the only situation where we run the iPXE test that it may be the old or new style of deployment. All other cases will expect only the new style of deployment.
* Because of this change, the `ncn-patch-upgrade-preflight-tests.yaml` suite is no longer needed. It isn't being used (it was intended to be used to handle the iPXE situation for CSM 1.5.1 upgrades) so this PR deletes it.
* I noticed that the upgrade scripts are …
> CASMINST-6523: Modify upgrade stage 0 iPXE check; create scripts to run Goss tests during CSM upgrades

- goss-testing/automated/ncn-k8s-combined-healthcheck-post-service-upgrade
- goss-testing/automated/run-ncn-tests.sh
- goss-testing/dat/goss-servers.cfg
- goss-testing/suites/ncn-healthcheck-master-single-post-service-upgrade.yaml
Add combined health check for use after CSM services are upgraded, but NCNs have not yet rolled by IUF management node rollout.
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6670
Drax (one expected failure):
```
ncn-m003:~ # /opt/cray/tests/install/ncn/automated/ncn-k8s-combined-healthcheck-post-service-upgrade
NCN and Kubernetes Checks (post CSM services upgrade)
------------------------------
Writing full output to /opt/cray/tests/install/logs/print_goss_json_results/20230718_212313.352790-566853-ygO1buGe/out
Running tests
Checking test results
Only errors will be printed to the screen
Result: FAIL
Source: http://ncn-m001.hmn:9008/ncn-healthcheck-master-single-post-service-upgrade
Test Name: Check hmnfd service
Description: Performs a basic health check on the hmnfd service. If this …
```
> Include post services install suite in ncn-k8s-combined-healthcheck
